export const CustomersList = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1 555-123-4567",
    address: "123 Main St, City, State, Country",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+1 555-987-6543",
    address: "456 Elm St, City, State, Country",
  },
  {
    id: "3",
    name: "Michael Johnson",
    email: "michael.johnson@example.com",
    phone: "+1 555-876-5432",
    address: "789 Oak St, City, State, Country",
  },
  {
    id: "4",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    phone: "+1 555-234-5678",
    address: "987 Pine St, City, State, Country",
  },
  {
    id: "5",
    name: "Robert Anderson",
    email: "robert.anderson@example.com",
    phone: "+1 555-765-4321",
    address: "654 Cedar St, City, State, Country",
  },
  {
    id: "6",
    name: "Sarah Wilson",
    email: "sarah.wilson@example.com",
    phone: "+1 555-345-6789",
    address: "321 Birch St, City, State, Country",
  },
  {
    id: "7",
    name: "David Brown",
    email: "david.brown@example.com",
    phone: "+1 555-876-5432",
    address: "789 Elm St, City, State, Country",
  },
  {
    id: "8",
    name: "Jennifer Taylor",
    email: "jennifer.taylor@example.com",
    phone: "+1 555-987-6543",
    address: "456 Oak St, City, State, Country",
  },
  {
    id: "9",
    name: "Daniel Clark",
    email: "daniel.clark@example.com",
    phone: "+1 555-234-5678",
    address: "987 Main St, City, State, Country",
  },
  {
    id: "10",
    name: "Jessica Turner",
    email: "jessica.turner@example.com",
    phone: "+1 555-765-4321",
    address: "654 Pine St, City, State, Country",
  },
  {
    id: "11",
    name: "Matthew Walker",
    email: "matthew.walker@example.com",
    phone: "+1 555-345-6789",
    address: "321 Cedar St, City, State, Country",
  },
  {
    id: "12",
    name: "Sophia Martinez",
    email: "sophia.martinez@example.com",
    phone: "+1 555-876-5432",
    address: "789 Birch St, City, State, Country",
  },
  {
    id: "13",
    name: "William Thompson",
    email: "william.thompson@example.com",
    phone: "+1 555-987-6543",
    address: "456 Elm St, City, State, Country",
  },
  {
    id: "14",
    name: "Olivia Lewis",
    email: "olivia.lewis@example.com",
    phone: "+1 555-234-5678",
    address: "987 Oak St, City, State, Country",
  },
  {
    id: "15",
    name: "James Green",
    email: "james.green@example.com",
    phone: "+1 555-765-4321",
    address: "654 Pine St, City, State, Country",
  },
  {
    id: "16",
    name: "Ava Hall",
    email: "ava.hall@example.com",
    phone: "+1 555-345-6789",
    address: "321 Cedar St, City, State, Country",
  },
  {
    id: "17",
    name: "Benjamin Young",
    email: "benjamin.young@example.com",
    phone: "+1 555-876-5432",
    address: "789 Elm St, City, State, Country",
  },
  {
    id: "18",
    name: "Mia Hill",
    email: "mia.hill@example.com",
    phone: "+1 555-987-6543",
    address: "456 Oak St, City, State, Country",
  },
  {
    id: "19",
    name: "Jacob Scott",
    email: "jacob.scott@example.com",
    phone: "+1 555-234-5678",
    address: "987 Main St, City, State, Country",
  },
  {
    id: "20",
    name: "Charlotte Adams",
    email: "charlotte.adams@example.com",
    phone: "+1 555-765-4321",
    address: "654 Pine St, City, State, Country",
  },
  {
    id: "21",
    name: "Joseph Baker",
    email: "joseph.baker@example.com",
    phone: "+1 555-345-6789",
    address: "321 Cedar St, City, State, Country",
  },
  {
    id: "22",
    name: "Harper Gonzalez",
    email: "harper.gonzalez@example.com",
    phone: "+1 555-876-5432",
    address: "789 Birch St, City, State, Country",
  },
  {
    id: "23",
    name: "Samuel Nelson",
    email: "samuel.nelson@example.com",
    phone: "+1 555-987-6543",
    address: "456 Elm St, City, State, Country",
  },
  {
    id: "24",
    name: "Evelyn Wright",
    email: "evelyn.wright@example.com",
    phone: "+1 555-234-5678",
    address: "987 Oak St, City, State, Country",
  },
  {
    id: "25",
    name: "Gabriel Mitchell",
    email: "gabriel.mitchell@example.com",
    phone: "+1 555-765-4321",
    address: "654 Pine St, City, State, Country",
  },
  {
    id: "26",
    name: "Sofia Perez",
    email: "sofia.perez@example.com",
    phone: "+1 555-345-6789",
    address: "321 Cedar St, City, State, Country",
  },
  {
    id: "27",
    name: "Carter Roberts",
    email: "carter.roberts@example.com",
    phone: "+1 555-876-5432",
    address: "789 Elm St, City, State, Country",
  },
  {
    id: "28",
    name: "Avery Turner",
    email: "avery.turner@example.com",
    phone: "+1 555-987-6543",
    address: "456 Oak St, City, State, Country",
  },
  {
    id: "29",
    name: "Jackson Cook",
    email: "jackson.cook@example.com",
    phone: "+1 555-234-5678",
    address: "987 Main St, City, State, Country",
  },
  {
    id: "30",
    name: "Scarlett Phillips",
    email: "scarlett.phillips@example.com",
    phone: "+1 555-765-4321",
    address: "654 Pine St, City, State, Country",
  },
  {
    id: "31",
    name: "Ryan Edwards",
    email: "ryan.edwards@example.com",
    phone: "+1 555-345-6789",
    address: "321 Cedar St, City, State, Country",
  },
  {
    id: "32",
    name: "Lucas Murphy",
    email: "lucas.murphy@example.com",
    phone: "+1 555-876-5432",
    address: "789 Birch St, City, State, Country",
  },
  {
    id: "33",
    name: "Chloe Rivera",
    email: "chloe.rivera@example.com",
    phone: "+1 555-987-6543",
    address: "456 Elm St, City, State, Country",
  },
  {
    id: "34",
    name: "Nathan Morgan",
    email: "nathan.morgan@example.com",
    phone: "+1 555-234-5678",
    address: "987 Oak St, City, State, Country",
  },
  {
    id: "35",
    name: "Lily Bell",
    email: "lily.bell@example.com",
    phone: "+1 555-765-4321",
    address: "654 Pine St, City, State, Country",
  },
  {
    id: "36",
    name: "Henry Reed",
    email: "henry.reed@example.com",
    phone: "+1 555-345-6789",
    address: "321 Cedar St, City, State, Country",
  },
  {
    id: "37",
    name: "Zoe Cooper",
    email: "zoe.cooper@example.com",
    phone: "+1 555-876-5432",
    address: "789 Elm St, City, State, Country",
  },
  {
    id: "38",
    name: "Liam Cox",
    email: "liam.cox@example.com",
    phone: "+1 555-987-6543",
    address: "456 Oak St, City, State, Country",
  },
  {
    id: "39",
    name: "Aria Gray",
    email: "aria.gray@example.com",
    phone: "+1 555-234-5678",
    address: "987 Main St, City, State, Country",
  },
  {
    id: "40",
    name: "Elijah Price",
    email: "elijah.price@example.com",
    phone: "+1 555-765-4321",
    address: "654 Pine St, City, State, Country",
  },
  {
    id: "41",
    name: "Grace Howard",
    email: "grace.howard@example.com",
    phone: "+1 555-345-6789",
    address: "321 Cedar St, City, State, Country",
  },
  {
    id: "42",
    name: "Alexander Ward",
    email: "alexander.ward@example.com",
    phone: "+1 555-876-5432",
    address: "789 Birch St, City, State, Country",
  },
  {
    id: "43",
    name: "Victoria Foster",
    email: "victoria.foster@example.com",
    phone: "+1 555-987-6543",
    address: "456 Elm St, City, State, Country",
  },
  {
    id: "44",
    name: "Sebastian Brooks",
    email: "sebastian.brooks@example.com",
    phone: "+1 555-234-5678",
    address: "987 Oak St, City, State, Country",
  },
  {
    id: "45",
    name: "Penelope Kelly",
    email: "penelope.kelly@example.com",
    phone: "+1 555-765-4321",
    address: "654 Pine St, City, State, Country",
  },
  {
    id: "46",
    name: "Julian Hayes",
    email: "julian.hayes@example.com",
    phone: "+1 555-345-6789",
    address: "321 Cedar St, City, State, Country",
  },
  {
    id: "47",
    name: "Mila Simmons",
    email: "mila.simmons@example.com",
    phone: "+1 555-876-5432",
    address: "789 Elm St, City, State, Country",
  },
  {
    id: "48",
    name: "Levi Patterson",
    email: "levi.patterson@example.com",
    phone: "+1 555-987-6543",
    address: "456 Oak St, City, State, Country",
  },
  {
    id: "49",
    name: "Lydia Gray",
    email: "lydia.gray@example.com",
    phone: "+1 555-234-5678",
    address: "987 Main St, City, State, Country",
  },
  {
    id: "50",
    name: "Gavin Hughes",
    email: "gavin.hughes@example.com",
    phone: "+1 555-765-4321",
    address: "654 Pine St, City, State, Country",
  },
];
